name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_RESOURCE_GROUP: RecoFlixResourceGroup
  AZURE_WEBAPP_NAME: recoflix-app-yomna
  AZURE_ACR_NAME: recoflixacryomna
  DOCKER_IMAGE_NAME: recoflix-app
  DOCKER_IMAGE_TAG: latest
  PORT: 5000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug: List repository contents
        run: |
          echo "Listing contents of the cloned repository root:"
          ls -R . # Lists all files and subdirectories recursively
          echo "Current working directory:"
          pwd # Prints the current working directory

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        # Nous allons laisser les chemins relatifs ici pour le moment.
        # Le débogage ci-dessus nous aidera à ajuster si nécessaire.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask test
        # Nous allons laisser les chemins relatifs ici pour le moment.
        # Le débogage ci-dessus nous aidera à ajuster si nécessaire.
        run: |
          python wsgi.py &
          sleep 5
          curl -f http://localhost:${{ env.PORT }} || exit 1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to ACR
        id: build-image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        # Le contexte de build Docker est le répertoire courant '.'
        run: |
          docker build . -t ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          images: '${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}'
