name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  AZURE_RESOURCE_GROUP: RecoFlixResourceGroup
  AZURE_WEBAPP_NAME: recoflix-app-yomna
  AZURE_ACR_NAME: recoflixacryomna
  DOCKER_IMAGE_NAME: recoflix-app
  DOCKER_IMAGE_TAG: latest
  PORT: 5000

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        # Exécute cette étape depuis le sous-dossier 'mon_flask_app'
        working-directory: mon_flask_app/ # Chemin correct par rapport à la racine du dépôt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask test
        # Exécute cette étape depuis le sous-dossier 'mon_flask_app'
        working-directory: mon_flask_app/ # Chemin correct par rapport à la racine du dépôt
        run: |
          python wsgi.py &
          sleep 5
          curl -f http://localhost:${{ env.PORT }} || exit 1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image to ACR
        id: build-image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.AZURE_ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        # Correction pour docker build : le chemin du contexte doit être 'mon_flask_app/'
      - run: |
          docker build mon_flask_app/ -t ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          docker push ${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          resource-group-name: ${{ env.AZURE_RESOURCE_GROUP }}
          images: '${{ env.AZURE_ACR_NAME }}.azurecr.io/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}'
